# Generated by Django 5.0.3 on 2024-05-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassControls', '0002_remove_categories_id_categories_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResponsibleFirstName', models.CharField(help_text='Add a first name for the responsible', max_length=100, verbose_name='Responsible First Name')),
                ('ResponsibleLastName', models.CharField(help_text='Add a last name for the responsible', max_length=100, verbose_name='Responsible Last Name')),
            ],
        ),
    ]
