# Generated by Django 5.0.3 on 2024-05-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassControls', '0003_responsibles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassTypeName', models.CharField(help_text='Add a class type name', max_length=50, verbose_name='Class Type')),
            ],
        ),
    ]
