# Generated by Django 5.0.3 on 2024-05-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassControls', '0008_evaluations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluations',
        ),
    ]
