# Generated by Django 5.0.3 on 2024-05-17 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassControls', '0010_planning_control_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning_control_classes',
            name='Category',
            field=models.ForeignKey(default=1, help_text='Select a category', on_delete=django.db.models.deletion.CASCADE, to='ClassControls.categories', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
