# Generated by Django 5.0.3 on 2024-05-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClassControls', '0011_planning_control_classes_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planning_control_classes',
            old_name='Carrer',
            new_name='Career',
        ),
        migrations.RenameField(
            model_name='planning_control_classes',
            old_name='Responsibble',
            new_name='Responsible',
        ),
    ]
